[package]
name = "camcam"
version = "0.1.0"
authors = ["Cameron Steffen <cam.steffen94@gmail.com>"]

[dependencies]
clap = "2.27.1"
env_logger = "0.4.2"
fnv = "1.0.6"
image = "0.12.3"
itertools = "0.5.9"
linked-hash-map = "0.5.0"
linked_hash_set = "0.1.1"
log = "0.3.7"
num = "0.1.37"
png = "0.6.2"
rand = "0.3.15"
rusttype = "0.2.1"
tempfile = "3.0.1"
vec_map = "0.8.0"

[[bin]]
name = "camcam"
path = "src/bin/camcam/main.rs"
