[package]
name = "camcam"
version = "0.1.0"
authors = ["Cameron Steffen <cam.steffen94@gmail.com>"]

[dependencies]
clap = "2.27.1"
env_logger = "0.4.2"
image = "0.12.3"
itertools = "0.5.9"
log = "0.3.7"
num = "0.1.37"
png = "0.6.2"
rand = "0.3.15"
rusttype = "0.2.1"
vec_map = "0.8.0"
