[package]
name = "camcam"
version = "0.1.0"
authors = ["Cameron Steffen <cam.steffen94@gmail.com>"]

[dependencies]
env_logger = "0.4.2"
getopts = "0.2.14"
image = "0.12.3"
itertools = "0.5.9"
log = "0.3.7"
num = "0.1.37"
png = "0.6.2"
rand = "0.3.15"
rusttype = "0.2.1"
serde = "0.9.14"
serde_derive = "0.9.14"
serde_json = "0.9.10"
